### ISSUE TITLE
Merge with sindresorhus/awesome

### ISSUE THREAD

**Issue by waldyrious** [emijrp/awesome-awesome#11]
It would be nice to merge efforts.
Clickable link: https://github.com/sindresorhus/awesome
/cc @sindresorhus

**Comment by emijrp** [comment]
I have a broader view about what to include in the awesome repo. Mine has sections for Astronomy, Biology, Arts, etc. I doubt I can add all that brainstorm to his repo...

**Comment by waldyrious** [comment]
That's a fair point. @sindresorhus care to comment?

**Comment by sindresorhus** [comment]
Happy to consider broader lists, but I would prefer to stay in the science/tech category.

**Comment by emijrp** [comment]
So, I prefer keeping my repo. Anyway there are dozens of "awesome-awesome" lists, so merging just this one would not take any real effect.

**Comment by waldyrious** [comment]
> So, I prefer keeping my repo.

Huh, I didn't expect that, since the contents of this repo are precisely geared (at least at the moment) towards science/technology. I understand if you want to expand, but as merely a compiler of other lists, you're dependent on other people taking the initiative to build lists for other subjects, and that results from their interests, which in the case of the github audience, is pretty much guaranteed to be centered in science/tech topics. For the minority of non-sci/tech awesome lists that will invariably appear, @sindresorhus' repo already has a Misc. section, so they wouldn't be lost anyway.

But don't take this as an attempt to convince you. I understand and respect your decision, and just wanted to put my reasoning in record.

> Anyway there are dozens of "awesome-awesome" lists, so merging just this one would not take any real effect.

Not dozens, in fact last I checked they were about half a dozen ([here's an attempt](https://github.com/t3chnoboy/awesome-awesome-awesome) at rounding them up, but I actually did a repo search to make sure I wasn't missing others). I did send messages to every one of them (which I could find), but they either didn't respond or chose to keep their repo:

* https://github.com/erichs/awesome-awesome/issues/12
* https://github.com/oyvindrobertsen/awesome-awesome/issues/9
* https://github.com/bradoyler/awesome-all/issues/6
* https://github.com/fleveque/awesome-awesomes/issues/16
* https://github.com/sindresorhus/awesome/issues/157

Which is kinda sad, since we end up duplicating work and competing instead of collaborating together. I wondered if merging the repos under an organization (instead of a user's repo) would ease the potential concerns of current repo owners, but given the lack of success of my attempt at launching the merge discussions, I don't feel like that effort would pay off either.
