### ISSUE TITLE
Awesome-Firefox and its alternatives

### ISSUE THREAD

**Issue by Hunter-Github** [emijrp/awesome-awesome#14]
https://github.com/pyllyukko/user.js is a very much important repo to track for every Firefox user. Other than that, there are very few resources to keep an eye on: AdBlockEdge/uBlock, NoScript, Cert Patrol, Greasemonkey, HTTPS Everywhere, Scrapbook X. The rest is mostly fluff.

**Comment by emijrp** [comment]
Would you like to create "awesome-firefox" repo with that info? I will link it.

**Comment by Hunter-Github** [comment]
Please have a look at https://github.com/Hunter-Github/awesome-firefox .

**Comment by emijrp** [comment]
Added, thanks! f268fc2be268f0f404282eef1936859445d8944a
